// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgK4C4mWZ4WOBBdXXtUBA0G8aAG_bUtKY',
    appId: '1:58456110891:web:40e89de475d1a55abbf76e',
    messagingSenderId: '58456110891',
    projectId: 'shopapp-7a7e5',
    authDomain: 'shopapp-7a7e5.firebaseapp.com',
    storageBucket: 'shopapp-7a7e5.appspot.com',
    measurementId: 'G-1B1F276NK3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqCqH1gpiOJlhO6Ta44FQCLTeKHSr3n3Q',
    appId: '1:58456110891:android:ab5b85a70e88a01cbbf76e',
    messagingSenderId: '58456110891',
    projectId: 'shopapp-7a7e5',
    storageBucket: 'shopapp-7a7e5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1UZIzllZcptk0GhIvic4wQ7ubN5zKn7s',
    appId: '1:58456110891:ios:60904d0c4be84a67bbf76e',
    messagingSenderId: '58456110891',
    projectId: 'shopapp-7a7e5',
    storageBucket: 'shopapp-7a7e5.appspot.com',
    iosClientId: '58456110891-jucndvm98r92okvuobtstmg22ppali7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.f0',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1UZIzllZcptk0GhIvic4wQ7ubN5zKn7s',
    appId: '1:58456110891:ios:60904d0c4be84a67bbf76e',
    messagingSenderId: '58456110891',
    projectId: 'shopapp-7a7e5',
    storageBucket: 'shopapp-7a7e5.appspot.com',
    iosClientId: '58456110891-jucndvm98r92okvuobtstmg22ppali7p.apps.googleusercontent.com',
    iosBundleId: 'com.example.f0',
  );
}
